services:
  mongodb:
    image: mongo:8
    container_name: portfolio-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: portfolio
    volumes:
      - mongodb_data:/data/db
    networks:
      - portfolio-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGO_URI: mongodb://mongodb:27017/portfolio
      JWT_ACCESS_SECRET: your-super-secret-access-key
      JWT_REFRESH_SECRET: your-super-secret-refresh-key
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@tranhieu.dev}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-Admin@123456}
      CLOUDINARY_CLOUD_NAME: digfoub3d
      CLOUDINARY_API_KEY: 687752919341867
      CLOUDINARY_API_SECRET: 3Kdbtvr92iHoaQaxlppxWkQtsb4


    volumes:
      - ./backend/src:/app/src
    depends_on:
      - mongodb
    networks:
      - portfolio-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
    depends_on:
      - backend
    networks:
      - portfolio-network

volumes:
  mongodb_data:

networks:
  portfolio-network:
    driver: bridge